# Adobe
DOMAIN-SUFFIX,cc-api-data.adobe.io,Adobe
DOMAIN-SUFFIX,adobesc.com,Adobe
DOMAIN-SUFFIX,adobe.com,Adobe

# Figma
DOMAIN-SUFFIX,s3-alpha-sig.figma.com,Figma
DOMAIN-SUFFIX,www.figma.com,Figma
DOMAIN-SUFFIX,static.figma.com,Figma

# Behance
DOMAIN-SUFFIX,behance.com,Behance
DOMAIN-SUFFIX,a5.behance.net,Behance
DOMAIN-SUFFIX,www.behance.net,Behance
DOMAIN-SUFFIX,mir-cdn-cf.behance.net,Behance
DOMAIN-SUFFIX,mir-s3-cdn-cf.behance.net,Behance

# Spotify
DOMAIN-SUFFIX,i.scdn.co,Spotify
DOMAIN-SUFFIX,p.scdn.co,Spotify
DOMAIN-SUFFIX,r.scdn.co,Spotify
DOMAIN-SUFFIX,t.scdn.co,Spotify
DOMAIN-SUFFIX,u.scdn.co,Spotify
DOMAIN-SUFFIX,audio-ec.spotify.com,Spotify
DOMAIN-SUFFIX,ap-gae2.spotify.com,Spotify
DOMAIN-SUFFIX,gae2-dealer2.spotify.com,Spotify
DOMAIN-SUFFIX,spotify.com,Spotify

# Grok
DOMAIN-SUFFIX,grok.com,Grok
DOMAIN-SUFFIX,api.x.ai,Grok
DOMAIN-SUFFIX,x.com,Grok

# awwwards
DOMAIN-SUFFIX,awwwards.com,awwwards
DOMAIN-SUFFIX,assets.awwwards.com,awwwards
DOMAIN-KEYWORD,awwwards,awwwards

# Claude
DOMAIN-SUFFIX,anthropic.com,Claude
DOMAIN-SUFFIX,claude.ai,Claude
DOMAIN-SUFFIX,statsig.com,Claude
DOMAIN-SUFFIX,featuregates.org,Claude
DOMAIN-SUFFIX,api.github.com,Claude
DOMAIN-SUFFIX,raw.githubusercontent.com,Claude
