[General]
#!include https://bava8u2znaj6bdzzjnfb.wgetcloud.online/link/4e7e2580-2b86-3482-9630-6f2e01d3cbba

[Proxy]
#!include https://bava8u2znaj6bdzzjnfb.wgetcloud.online/link/4e7e2580-2b86-3482-9630-6f2e01d3cbba

[Proxy Group]
#!include https://kailous.github.io/SurgeConfig/Modules/ProxyGroup.conf

[Rule]
#!include https://bava8u2znaj6bdzzjnfb.wgetcloud.online/link/4e7e2580-2b86-3482-9630-6f2e01d3cbba

[URL Rewrite]
#!include https://kailous.github.io/SurgeConfig/Modules/URLRewrite.conf

[MITM]
#!include https://kailous.github.io/SurgeConfig/Modules/MITM.conf
