[General]
#!include {{SURGE_SUB_URL}}

[Proxy]
#!include {{SURGE_SUB_URL}}

[Proxy Group]
#!include https://kailous.github.io/SurgeConfig/Modules/ProxyGroup.conf

[Rule]
# 先引入自定义规则（自上而下匹配）
#!include https://kailous.github.io/SurgeConfig/Modules/CustomRule.conf
# 机场默认规则
#!include {{SURGE_SUB_URL}}

[URL Rewrite]
#!include https://kailous.github.io/SurgeConfig/Modules/URLRewrite.conf

[MITM]
#!include https://kailous.github.io/SurgeConfig/Modules/MITM.conf
