[General]
loglevel = notify
dns-server = 223.5.5.5, 114.114.114.114, system
skip-proxy = 127.0.0.1, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 100.64.0.0/10, 17.0.0.0/8, localhost, *.local, *.crashlytics.com
allow-wifi-access = false
enhanced-mode-by-rule = false
exclude-simple-hostnames = true
show-error-page-for-reject = true
ipv6 = true
replica = false
http-listen = 0.0.0.0:8234
socks5-listen = 0.0.0.0:8235
wifi-access-http-port = 6152
wifi-access-socks5-port = 6153
internet-test-url = http://wifi.vivo.com.cn/generate_204
proxy-test-url = http://cp.cloudflare.com/generate_204
test-timeout = 5

[Proxy]
#!include {{SURGE_SUB_URL}}?list=surge

[Proxy Group]
#!include https://kailous.github.io/SurgeConfig/Modules/ProxyGroup.conf

[Rule]
#!include https://kailous.github.io/SurgeConfig/Modules/CustomRule.conf
# 最终兜底规则
FINAL, DIRECT

[URL Rewrite]
#!include https://kailous.github.io/SurgeConfig/Modules/URLRewrite.conf

[MITM]
#!include https://kailous.github.io/SurgeConfig/Modules/MITM.conf
